### ISSUE TITLE
502 gateway error when attempting to use Icecat streaming 

### ISSUE THREAD

**Issue by jorge-aparicio** [raveberry/raveberry#107]
Hello, I've been messing around trying to get raveberry to work in my setup. I've tested the default config and that seems to work fine. However, when I try to forward the raveberry nginx proxy through my traefik proxy the stream link no longer functions and only gives me a 502 bad gateway error. Does anyone have any ideas on what I need to do to get it working? 

Below is my compose config:

```
version: '3'

volumes:
  static-files:
  songs-cache:
    # If you want to access downloaded files on your host system,
    # uncomment the following lines and choose a folder.
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/media'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=raveberry
      - POSTGRES_USER=raveberry
      - POSTGRES_PASSWORD=raveberry
    restart: always
    networks:
      - internal
  redis:
    image: redis
    restart: always
    networks:
      - internal
      
  icecast:
    image: raveberry/raveberry-icecast
    environment:
      ICECAST_ADMIN_PASSWORD: "password"
      STREAM_USERNAME: "name"
      STREAM_PASSWORD: "password"
      STREAM_NOAUTH: "0"
    # uncomment this port mapping if you need to access icecast's web interface
    #ports:
    #  - 8000:8000
    # uncomment these lines with a path to a custom icecast config
    #volumes:
    #  - /path/to/icecast.xml:/etc/icecast.xml
    restart: always
  mopidy:
    image: raveberry/raveberry-mopidy
    environment:
      # optional spotify and soundcloud settings
      - SPOTIFY_USERNAME
      - SPOTIFY_PASSWORD
      - SPOTIFY_CLIENT_ID
      - SPOTIFY_CLIENT_SECRET
      - SOUNDCLOUD_AUTH_TOKEN
    volumes:
      - songs-cache:/Music/raveberry
      # If you want to use spotify, 
      # uncomment this line with a path to a config file containing the spotify credentials
      # - /path/to/mopidy.conf:/config/mopidy_icecast.conf
    command: bash -c "/usr/bin/mopidy --config /config/mopidy_icecast.conf"
    depends_on:
      - icecast
    restart: always
    networks:
      - internal
      
  daphne:
    image: raveberry/raveberry
    environment:
      ADMIN_PASSWORD: "password"
      MOD_PASSWORD: "password"
      DOCKER: 1
      DOCKER_ICECAST: 1
    expose:
      - 9000
    volumes:
      - static-files:/opt/raveberry/static
      - songs-cache:/Music/raveberry
    depends_on:
      - db
      - redis
      - mopidy
      - icecast
    restart: always
    networks:
      - internal
      
  nginx:
    image: raveberry/raveberry-nginx
    expose:
      - "80"
    volumes:
      - static-files:/usr/share/nginx/static
    depends_on:
      - daphne
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.raveberry.rule=Host(`music.domain.tld`)"
      - "traefik.http.routers.raveberry.entrypoints=websecure"
      - "traefik.http.routers.raveberry.tls=true"
      - "traefik.http.routers.raveberry.tls.options=default"
      - "traefik.http.services.raveberry.loadbalancer.server.port=80"
       # add security middleware
      - "traefik.http.routers.raveberry.middlewares=security-headers"
    networks:
      - proxy-tier
      - internal

networks:
  proxy-tier:
    external: true
  internal:
    external: false

```
